name: Render Keep-Alive 24/7

on:
  schedule:
    # Dispara a cada 10 minutos
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Web Service
        run: |
          curl -sS -I "https://victorbot-xkuh.onrender.com" || true
